# app/migrations/script.py.mako
"""add_privacy_accepted_to_user

Revision ID: 430b09921997
Revises: df983083319d
Create Date: 2026-07-02 12:02:04.893850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430b09921997'
down_revision = 'df983083319d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('privacy_accepted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privacy_accepted')
    # ### end Alembic commands ###
