// ─────────────────────────────────────────────
// Masking Tokens
// ─────────────────────────────────────────────

export const MASKING_TOKENS = {
  // Financial
  CREDIT_CARD: '[CARD-REDACTED]',
  BANK_ACCOUNT: '[BANK-ACCOUNT-REDACTED]',
  IBAN: '[IBAN-REDACTED]',
  TAX_ID: '[TAX-ID-REDACTED]',
  PAN_CARD: '[PAN-REDACTED]',
  SALARY: '[SALARY-REDACTED]',
  FINANCIAL_DATA: '[FINANCIAL-DATA-REDACTED]',

  // PII
  EMAIL: '[EMAIL-REDACTED]',
  PHONE: '[PHONE-REDACTED]',
  AADHAAR: '[AADHAAR-REDACTED]',
  SSN: '[SSN-REDACTED]',
  PASSPORT: '[PASSPORT-REDACTED]',
  NATIONAL_ID: '[ID-REDACTED]',
  DATE_OF_BIRTH: '[DOB-REDACTED]',
  ADDRESS: '[ADDRESS-REDACTED]',
  FULL_NAME: '[NAME-REDACTED]',
  MEDICAL: '[MEDICAL-DATA-REDACTED]',

  // Confidential
  API_KEY: '[API-KEY-REDACTED]',
  PASSWORD: '[PASSWORD-REDACTED]',
  SECRET: '[SECRET-REDACTED]',
  JWT_TOKEN: '[TOKEN-REDACTED]',
  AWS_KEY: '[AWS-KEY-REDACTED]',
  GITHUB_PAT: '[GITHUB-PAT-REDACTED]',
  SOURCE_CODE: '[CODE-REDACTED]',
  CREDENTIALS: '[CREDENTIALS-REDACTED]',

  // IP
  PROPRIETARY: '[PROPRIETARY-DATA-REDACTED]',

  // Generic fallback
  GENERIC: '[REDACTED]',
} as const

export type MaskingToken = (typeof MASKING_TOKENS)[keyof typeof MASKING_TOKENS]

// Map detection type -> masking token
export const DETECTION_TYPE_TO_TOKEN: Record<string, MaskingToken> = {
  credit_card: MASKING_TOKENS.CREDIT_CARD,
  bank_account: MASKING_TOKENS.BANK_ACCOUNT,
  iban: MASKING_TOKENS.IBAN,
  pan_card: MASKING_TOKENS.PAN_CARD,
  tax_id: MASKING_TOKENS.TAX_ID,
  salary: MASKING_TOKENS.SALARY,
  financial_data: MASKING_TOKENS.FINANCIAL_DATA,
  email: MASKING_TOKENS.EMAIL,
  phone: MASKING_TOKENS.PHONE,
  aadhaar: MASKING_TOKENS.AADHAAR,
  ssn: MASKING_TOKENS.SSN,
  passport: MASKING_TOKENS.PASSPORT,
  national_id: MASKING_TOKENS.NATIONAL_ID,
  date_of_birth: MASKING_TOKENS.DATE_OF_BIRTH,
  address: MASKING_TOKENS.ADDRESS,
  full_name: MASKING_TOKENS.FULL_NAME,
  medical: MASKING_TOKENS.MEDICAL,
  api_key: MASKING_TOKENS.API_KEY,
  password: MASKING_TOKENS.PASSWORD,
  secret: MASKING_TOKENS.SECRET,
  jwt_token: MASKING_TOKENS.JWT_TOKEN,
  aws_key: MASKING_TOKENS.AWS_KEY,
  github_pat: MASKING_TOKENS.GITHUB_PAT,
  source_code: MASKING_TOKENS.SOURCE_CODE,
  credentials: MASKING_TOKENS.CREDENTIALS,
  proprietary: MASKING_TOKENS.PROPRIETARY,
}
