// ─────────────────────────────────────────────
// Confidential / Business Data Rules
// ─────────────────────────────────────────────

import type { DetectionRule } from '../schema'

export const confidentialRules: DetectionRule[] = [
  {
    id: 'confidential.aws_access_key',
    category: 'CONFIDENTIAL',
    type: 'aws_key',
    label: 'AWS Access Key',
    pattern: /\b(AKIA|ABIA|ACCA|ASIA)[A-Z0-9]{16}\b/g,
    severity: 'critical',
    enabled: true,
    description: 'AWS IAM Access Key ID',
  },
  {
    id: 'confidential.aws_secret_key',
    category: 'CONFIDENTIAL',
    type: 'aws_key',
    label: 'AWS Secret Key',
    pattern: /\b[A-Za-z0-9\/+]{40}\b/g,
    severity: 'critical',
    enabled: true,
    description: 'AWS Secret Access Key (40-char base64)',
  },
  {
    id: 'confidential.github_pat',
    category: 'CONFIDENTIAL',
    type: 'github_pat',
    label: 'GitHub Personal Access Token',
    pattern: /\bghp_[A-Za-z0-9]{36}\b|\bgho_[A-Za-z0-9]{36}\b|\bghr_[A-Za-z0-9]{36}\b/g,
    severity: 'critical',
    enabled: true,
    description: 'GitHub Personal Access Token',
  },
  {
    id: 'confidential.jwt_token',
    category: 'CONFIDENTIAL',
    type: 'jwt_token',
    label: 'JWT Token',
    pattern: /\beyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\b/g,
    severity: 'critical',
    enabled: true,
    description: 'JSON Web Token',
  },
  {
    id: 'confidential.google_api_key',
    category: 'CONFIDENTIAL',
    type: 'api_key',
    label: 'Google API Key',
    pattern: /\bAIza[0-9A-Za-z\-_]{35}\b/g,
    severity: 'critical',
    enabled: true,
    description: 'Google API Key',
  },
  {
    id: 'confidential.private_key',
    category: 'CONFIDENTIAL',
    type: 'credentials',
    label: 'Private Key / Certificate',
    pattern: /-----BEGIN\s+(?:RSA\s+)?PRIVATE\s+KEY-----/g,
    severity: 'critical',
    enabled: true,
    description: 'PEM private key or certificate',
  },
  {
    id: 'confidential.password_in_text',
    category: 'CONFIDENTIAL',
    type: 'password',
    label: 'Password in Text',
    pattern: /\b(?:password|passwd|pwd|pass)[\s]*[=:]+[\s]*[^\s]{6,}\b/gi,
    severity: 'critical',
    enabled: true,
    description: 'Password assignment pattern in text',
  },
  {
    id: 'confidential.secret_in_text',
    category: 'CONFIDENTIAL',
    type: 'secret',
    label: 'Secret / Token in Text',
    pattern: /\b(?:secret|token|api_key|apikey|auth_token|access_token)[\s]*[=:]+[\s]*[^\s]{8,}\b/gi,
    severity: 'critical',
    enabled: true,
    description: 'Secret or token assignment pattern',
  },
  {
    id: 'confidential.source_code',
    category: 'CONFIDENTIAL',
    type: 'source_code',
    label: 'Source Code',
    // Multi-line code pattern detection via heuristics
    pattern: /\b(?:function|def\s+\w+|class\s+\w+|import\s+\w+|const\s+\w+\s*=|let\s+\w+\s*=|var\s+\w+\s*=|#include|namespace\s+\w+|public\s+(?:class|static|void))\b/g,
    severity: 'high',
    enabled: true,
    description: 'Source code keywords and structure',
  },
  {
    id: 'confidential.internal_label',
    category: 'CONFIDENTIAL',
    type: 'credentials',
    label: 'Confidential Document Label',
    pattern: /\b(?:confidential|internal\s+use\s+only|not\s+for\s+distribution|proprietary|strictly\s+private|do\s+not\s+share)\b/gi,
    severity: 'high',
    enabled: true,
    description: 'Document classification labels',
  },
]
