# app/migrations/script.py.mako
"""add_deletion_and_inactivity_policies

Revision ID: b68b2d18c769
Revises: 430b09921997
Create Date: 2026-07-02 14:12:43.948557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68b2d18c769'
down_revision = '430b09921997'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deactivation_reason', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('pre_deletion_email_sent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'deleted_user_logs' not in tables:
        op.create_table(
            'deleted_user_logs',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('user_id', sa.String(length=255), nullable=False),
            sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_user_logs')
    op.drop_column('users', 'pre_deletion_email_sent')
    op.drop_column('users', 'deactivation_reason')
    op.drop_column('users', 'deactivated_at')
    # ### end Alembic commands ###
