// ─────────────────────────────────────────────
// PII Detection Rules
// ─────────────────────────────────────────────

import type { DetectionRule } from '../schema'

export const piiRules: DetectionRule[] = [
  {
    id: 'pii.email',
    category: 'PII',
    type: 'email',
    label: 'Email Address',
    pattern: /\b[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}\b/g,
    severity: 'high',
    enabled: true,
    description: 'RFC 5322 email address pattern',
  },
  {
    id: 'pii.phone_in',
    category: 'PII',
    type: 'phone',
    label: 'Phone Number (India)',
    pattern: /(?:\+91[\s\-]?)?(?:0)?[6-9][0-9]{9}\b/g,
    severity: 'high',
    enabled: true,
    description: 'Indian mobile and landline numbers',
  },
  {
    id: 'pii.phone_us',
    category: 'PII',
    type: 'phone',
    label: 'Phone Number (US)',
    pattern: /(?:\+1[\s\-]?)?\(?[2-9][0-9]{2}\)?[\s\-]?[0-9]{3}[\s\-]?[0-9]{4}\b/g,
    severity: 'high',
    enabled: true,
    description: 'US phone number formats',
  },
  {
    id: 'pii.aadhaar',
    category: 'PII',
    type: 'aadhaar',
    label: 'Aadhaar Number (India)',
    pattern: /\b[2-9]{1}[0-9]{3}[\s\-]?[0-9]{4}[\s\-]?[0-9]{4}\b/g,
    validatorId: 'verhoeff',
    severity: 'critical',
    enabled: true,
    description: 'Indian Aadhaar 12-digit unique identity number',
  },
  {
    id: 'pii.ssn',
    category: 'PII',
    type: 'ssn',
    label: 'SSN (USA)',
    pattern: /\b(?!000|666|9[0-9]{2})[0-9]{3}[-\s]?(?!00)[0-9]{2}[-\s]?(?!0000)[0-9]{4}\b/g,
    severity: 'critical',
    enabled: true,
    description: 'US Social Security Number',
  },
  {
    id: 'pii.passport_in',
    category: 'PII',
    type: 'passport',
    label: 'Passport Number (India)',
    pattern: /\b[A-PR-WYa-pr-wy][1-9][0-9]{5}[0-9Nn][0-9]\b/g,
    severity: 'critical',
    enabled: true,
    description: 'Indian passport number format',
  },
  {
    id: 'pii.date_of_birth',
    category: 'PII',
    type: 'date_of_birth',
    label: 'Date of Birth',
    pattern: /\b(?:dob|date\s+of\s+birth|birth\s+date|born\s+on|d\.o\.b)[\s:=\-]*(?:0?[1-9]|[12][0-9]|3[01])[\s\/\-\.](?:0?[1-9]|1[012])[\s\/\-\.](?:19|20)[0-9]{2}\b/gi,
    severity: 'high',
    enabled: true,
    description: 'Date of birth with contextual keyword',
  },
  {
    id: 'pii.ip_address',
    category: 'PII',
    type: 'ip_address',
    label: 'IP Address',
    pattern: /\b(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/g,
    severity: 'medium',
    enabled: true,
    description: 'IPv4 address',
  },
]
