// ─────────────────────────────────────────────
// PII Detection Rules
// Enhanced with MVP patterns
// ─────────────────────────────────────────────

import type { DetectionRule } from '../schema'

export const piiRules: DetectionRule[] = [
  {
    id: 'pii.email',
    category: 'PII',
    type: 'email',
    label: 'Email Address',
    pattern: /\b([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})\b/g,
    severity: 'medium',
    enabled: true,
    description: 'RFC 5322 email address pattern',
  },
  {
    id: 'pii.aadhaar',
    category: 'PII',
    type: 'aadhaar',
    label: 'Aadhaar (UID) Number',
    // 12-digit number; allows common OCR misreads (O=0, I=1, B=8, S=5, Z=2)
    pattern: /(?<![/])([2-9Z][0-9OIBSZ]{3}[\s-]?[0-9OIBSZ]{4}[\s-]?[0-9OIBSZ]{4})\b/gi,
    validatorId: 'verhoeff',
    requireContext: true,
    severity: 'critical',
    enabled: true,
    description: 'Indian Aadhaar 12-digit ID with Verhoeff check',
  },
  {
    id: 'pii.phone_in',
    category: 'PII',
    type: 'phone',
    label: 'Indian Mobile Number',
    pattern: /\b(?:\+91[\s-]?)?([6-9]\d{9})\b/g,
    requireContext: true,
    severity: 'medium',
    enabled: true,
    description: 'Indian mobile number starting with 6-9',
  },
  {
    id: 'pii.us_ssn',
    category: 'PII',
    type: 'ssn',
    label: 'US Social Security Number',
    pattern: /\b(\d{3}-\d{2}-\d{4})\b/g,
    requireContext: true,
    severity: 'high',
    enabled: true,
    description: 'US SSN in 3-2-4 format',
  },
  {
    id: 'pii.passport_in',
    category: 'PII',
    type: 'passport',
    label: 'Indian Passport Number',
    pattern: /\b([A-Z][0-9]{7,8})\b/gi,
    requireContext: true,
    severity: 'high',
    enabled: true,
    description: 'Standard Indian passport format',
  },
  {
    id: 'pii.indian_dl',
    category: 'PII',
    type: 'national_id',
    label: 'Indian Driving Licence',
    // SS RR YYYY NNNNNNN format (e.g. DL 13 2011 0123456)
    pattern: /\b([A-Z]{2}[\s-]?[0-9]{2}[\s-]?[0-9]{4}[\s-]?[0-9]{7})\b/gi,
    requireContext: true,
    severity: 'high',
    enabled: true,
    description: 'Indian Driving Licence number',
  },
  {
    id: 'pii.passport_mrz_l1',
    category: 'PII',
    type: 'passport',
    label: 'Passport MRZ (Line 1)',
    pattern: /(P[<{([]?[A-Z<{([]]{40,44})/gi,
    severity: 'critical',
    enabled: true,
    description: 'Passport Machine Readable Zone - Line 1',
  },
  {
    id: 'pii.passport_mrz_l2',
    category: 'PII',
    type: 'passport',
    label: 'Passport MRZ (Line 2)',
    // Structure: 9-10 chars (PN), 3 chars (Country), 7 chars (DOB), 1 char (Sex), 7 chars (Expiry), 14 chars (Personal No)
    pattern: /([A-Z0-9<]{9,10}[A-Z1]{3}[0-9]{6,7}[MF<]{1}[0-9]{6,7}[A-Z0-9<]{10,16})/gi,
    severity: 'critical',
    enabled: true,
    description: 'Passport Machine Readable Zone - Line 2',
  },
  {
    id: 'pii.voter_id',
    category: 'PII',
    type: 'national_id',
    label: 'Voter ID / EPIC Number',
    pattern: /\b([A-Z]{3}[0-9]{7})\b/g,
    requireContext: true,
    severity: 'high',
    enabled: true,
    description: 'Indian Election Commission Voter ID',
  },
  {
    id: 'pii.abha_id',
    category: 'PII',
    type: 'medical',
    label: 'ABHA Health ID',
    pattern: /\b(\d{2}-\d{4}-\d{4}-\d{4})\b/g,
    requireContext: true,
    severity: 'high',
    enabled: true,
    description: 'Ayushman Bharat Health Account ID',
  },
  {
    id: 'pii.date_of_birth',
    category: 'PII',
    type: 'date_of_birth',
    label: 'Date (potential DOB)',
    pattern: /\b(\d{1,2}[/.-]\d{1,2}[/.-]\d{2,4})\b/g,
    requireContext: true,
    severity: 'medium',
    enabled: true,
    description: 'Matches date format when context triggers nearby',
  },
  {
    id: 'pii.ipv4',
    category: 'PII',
    type: 'ip_address',
    label: 'IPv4 Address',
    pattern: /\b((?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\b/g,
    requireContext: true,
    severity: 'low',
    enabled: true,
    description: 'IPv4 network address with context',
  },
]
